services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: brewchemy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brewchemy
    ports:
      - "5433:5432"   # host 5433 -> container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 10000 --reload --reload-dir /app/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:brewchemy@db:5432/brewchemy
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      OAUTHLIB_INSECURE_TRANSPORT: "1"
      OAUTHLIB_RELAX_TOKEN_SCOPE: "1"
    depends_on:
      - db
    ports:
      - "10000:10000"
    volumes:
      - ./backend/app:/app/app:rw
    env_file:
      - ./backend/.env.docker

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"

volumes:
  pgdata:
