export const beerStyles = [
    {
        "name": "American Amber Ale",
        "initialABV": 4.5,
        "finalABV": 6.2,
        "initialIBU": 25,
        "finalIBU": 40,
        "initialEBC": 18,
        "finalEBC": 30,
        "initialOG": 1.045,
        "finalOG": 1.060,
        "initialBuGu": 0.50,
        "finalBuGu": 0.65,
        "initialFG": 1.010,
        "finalFG": 1.015
    },
    {
        "name": "American Barleywine",
        "initialABV": 8.0,
        "finalABV": 12.0,
        "initialIBU": 35,
        "finalIBU": 70,
        "initialEBC": 30,
        "finalEBC": 70,
        "initialOG": 1.070,
        "finalOG": 1.100,
        "initialBuGu": 0.50,
        "finalBuGu": 0.80,
        "initialFG": 1.010,
        "finalFG": 1.020
    },
    {
        "name": "American Black Ale",
        "initialABV": 5.5,
        "finalABV": 8.0,
        "initialIBU": 40,
        "finalIBU": 70,
        "initialEBC": 40,
        "finalEBC": 80,
        "initialOG": 1.050,
        "finalOG": 1.070,
        "initialBuGu": 0.50,
        "finalBuGu": 0.75,
        "initialFG": 1.010,
        "finalFG": 1.020
    },
    {
        "name": "American Blonde Ale",
        "initialABV": 3.8,
        "finalABV": 5.5,
        "initialIBU": 15,
        "finalIBU": 28,
        "initialEBC": 8,
        "finalEBC": 18,
        "initialOG": 1.040,
        "finalOG": 1.055,
        "initialBuGu": 0.30,
        "finalBuGu": 0.50,
        "initialFG": 1.008,
        "finalFG": 1.012
    },
    {
        "name": "American Brown Ale",
        "initialABV": 4.3,
        "finalABV": 6.2,
        "initialIBU": 20,
        "finalIBU": 30,
        "initialEBC": 35,
        "finalEBC": 60,
        "initialOG": 1.045,
        "finalOG": 1.060,
        "initialBuGu": 0.50,
        "finalBuGu": 0.60,
        "initialFG": 1.010,
        "finalFG": 1.016
    },
    {
        "name": "American Cream Ale",
        "initialABV": 4.2,
        "finalABV": 5.6,
        "initialIBU": 15,
        "finalIBU": 25,
        "initialEBC": 8,
        "finalEBC": 16,
        "initialOG": 1.040,
        "finalOG": 1.050,
        "initialBuGu": 0.20,
        "finalBuGu": 0.30,
        "initialFG": 1.008,
        "finalFG": 1.012
    },
    {
        "name": "American Double IPA",
        "initialABV": 7.5,
        "finalABV": 10.0,
        "initialIBU": 60,
        "finalIBU": 100,
        "initialEBC": 12,
        "finalEBC": 20,
        "initialOG": 1.070,
        "finalOG": 1.085,
        "initialBuGu": 0.60,
        "finalBuGu": 0.80,
        "initialFG": 1.010,
        "finalFG": 1.016
    },
    {
        "name": "American IPA",
        "initialABV": 5.5,
        "finalABV": 7.5,
        "initialIBU": 40,
        "finalIBU": 70,
        "initialEBC": 10,
        "finalEBC": 20,
        "initialOG": 1.056,
        "finalOG": 1.070,
        "initialBuGu": 0.70,
        "finalBuGu": 1.00,
        "initialFG": 1.008,
        "finalFG": 1.014
    },
    {
        "name": "American Imperial IPA",
        "initialABV": 7.5,
        "finalABV": 10.0,
        "initialIBU": 60,
        "finalIBU": 120,
        "initialEBC": 8,
        "finalEBC": 16,
        "initialOG": 1.070,
        "finalOG": 1.090,
        "initialBuGu": 0.70,
        "finalBuGu": 1.00,
        "initialFG": 1.010,
        "finalFG": 1.020
    },
    {
        "name": "American Lager",
        "initialABV": 4.2,
        "finalABV": 5.3,
        "initialIBU": 8,
        "finalIBU": 18,
        "initialEBC": 4,
        "finalEBC": 7,
        "initialOG": 1.040,
        "finalOG": 1.050,
        "initialBuGu": 0.20,
        "finalBuGu": 0.35,
        "initialFG": 1.004,
        "finalFG": 1.010
    },
    {
        "name": "American Light Lager",
        "initialABV": 3.2,
        "finalABV": 4.2,
        "initialIBU": 8,
        "finalIBU": 12,
        "initialEBC": 2,
        "finalEBC": 8,
        "initialOG": 1.028,
        "finalOG": 1.040,
        "initialBuGu": 0.15,
        "finalBuGu": 0.30,
        "initialFG": 1.004,
        "finalFG": 1.010
    },
    {
        "name": "American Pale Ale",
        "initialABV": 4.5,
        "finalABV": 6.0,
        "initialIBU": 30,
        "finalIBU": 45,
        "initialEBC": 8,
        "finalEBC": 14,
        "initialOG": 1.045,
        "finalOG": 1.060,
        "initialBuGu": 0.50,
        "finalBuGu": 0.70,
        "initialFG": 1.010,
        "finalFG": 1.016
    },
    {
        "name": "American Porter",
        "initialABV": 4.5,
        "finalABV": 6.5,
        "initialIBU": 25,
        "finalIBU": 50,
        "initialEBC": 20,
        "finalEBC": 40,
        "initialOG": 1.050,
        "finalOG": 1.070,
        "initialBuGu": 0.40,
        "finalBuGu": 0.60,
        "initialFG": 1.010,
        "finalFG": 1.016
    },
    {
        "name": "American Malt Liquor",
        "initialABV": "6.0",
        "finalABV": "9.0",
        "initialIBU": "10",
        "finalIBU": "30",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.10",
        "finalBuGu": "0.30"
    },
    {
        "name": "American Pale Ale",
        "initialABV": "4.5",
        "finalABV": "6.2",
        "initialIBU": "30",
        "finalIBU": "50",
        "initialEBC": "10",
        "finalEBC": "20",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.50",
        "finalBuGu": "0.80"
    },
    {
        "name": "American Porter",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "25",
        "finalIBU": "50",
        "initialEBC": "25",
        "finalEBC": "50",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "American Stout",
        "initialABV": "5.0",
        "finalABV": "7.0",
        "initialIBU": "35",
        "finalIBU": "50",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "American Strong Ale",
        "initialABV": "6.5",
        "finalABV": "9.5",
        "initialIBU": "35",
        "finalIBU": "60",
        "initialEBC": "10",
        "finalEBC": "25",
        "initialOG": "1.060",
        "finalOG": "1.090",
        "initialFG": "1.012",
        "finalFG": "1.020",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "American Wheat Beer",
        "initialABV": "4.0",
        "finalABV": "5.5",
        "initialIBU": "15",
        "finalIBU": "30",
        "initialEBC": "4",
        "finalEBC": "12",
        "initialOG": "1.040",
        "finalOG": "1.055",
        "initialFG": "1.008",
        "finalFG": "1.013",
        "initialBuGu": "0.30",
        "finalBuGu": "0.55"
    },
    {
        "name": "Barleywine",
        "initialABV": "8.0",
        "finalABV": "12.0",
        "initialIBU": "35",
        "finalIBU": "70",
        "initialEBC": "14",
        "finalEBC": "24",
        "initialOG": "1.070",
        "finalOG": "1.120",
        "initialFG": "1.010",
        "finalFG": "1.030",
        "initialBuGu": "0.50",
        "finalBuGu": "0.80"
    },
    {
        "name": "Belgian Ale",
        "initialABV": "4.0",
        "finalABV": "7.0",
        "initialIBU": "15",
        "finalIBU": "30",
        "initialEBC": "10",
        "finalEBC": "30",
        "initialOG": "1.040",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "Belgian Blond Ale",
        "initialABV": "6.0",
        "finalABV": "7.5",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "4",
        "finalEBC": "10",
        "initialOG": "1.070",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.25",
        "finalBuGu": "0.40"
    },
    {
        "name": "Belgian Dark Ale",
        "initialABV": "6.0",
        "finalABV": "10.0",
        "initialIBU": "20",
        "finalIBU": "40",
        "initialEBC": "30",
        "finalEBC": "75",
        "initialOG": "1.070",
        "finalOG": "1.100",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "Belgian Dubbel",
        "initialABV": "6.0",
        "finalABV": "7.6",
        "initialIBU": "15",
        "finalIBU": "25",
        "initialEBC": "20",
        "finalEBC": "35",
        "initialOG": "1.070",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "Belgian Golden Strong Ale",
        "initialABV": "7.5",
        "finalABV": "10.5",
        "initialIBU": "25",
        "finalIBU": "35",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Belgian IPA",
        "initialABV": "6.0",
        "finalABV": "7.5",
        "initialIBU": "40",
        "finalIBU": "70",
        "initialEBC": "8",
        "finalEBC": "18",
        "initialOG": "1.060",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.50",
        "finalBuGu": "0.80"
    },
    {
        "name": "Belgian Lambic",
        "initialABV": "5.0",
        "finalABV": "6.5",
        "initialIBU": "10",
        "finalIBU": "35",
        "initialEBC": "10",
        "finalEBC": "30",
        "initialOG": "1.040",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Belgian Strong Ale",
        "initialABV": "7.5",
        "finalABV": "10.5",
        "initialIBU": "30",
        "finalIBU": "50",
        "initialEBC": "14",
        "finalEBC": "22",
        "initialOG": "1.070",
        "finalOG": "1.100",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Belgian Strong Dark Ale",
        "initialABV": "8.0",
        "finalABV": "12.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.080",
        "finalOG": "1.120",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Belgian Tripel",
        "initialABV": "7.5",
        "finalABV": "9.5",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "15",
        "finalEBC": "25",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Berliner Weisse",
        "initialABV": "3.1",
        "finalABV": "4.2",
        "initialIBU": "8",
        "finalIBU": "16",
        "initialEBC": "2",
        "finalEBC": "8",
        "initialOG": "1.030",
        "finalOG": "1.036",
        "initialFG": "1.004",
        "finalFG": "1.008",
        "initialBuGu": "0.15",
        "finalBuGu": "0.30"
    },
    {
        "name": "Bière de Garde",
        "initialABV": "6.5",
        "finalABV": "8.5",
        "initialIBU": "18",
        "finalIBU": "28",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Black IPA",
        "initialABV": "6.0",
        "finalABV": "7.5",
        "initialIBU": "40",
        "finalIBU": "80",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.50",
        "finalBuGu": "0.75"
    },
    {
        "name": "Bock",
        "initialABV": "6.3",
        "finalABV": "7.2",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "14",
        "finalEBC": "22",
        "initialOG": "1.070",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.25",
        "finalBuGu": "0.35"
    },
    {
        "name": "Bohemian Pilsner",
        "initialABV": "4.2",
        "finalABV": "5.4",
        "initialIBU": "35",
        "finalIBU": "45",
        "initialEBC": "10",
        "finalEBC": "20",
        "initialOG": "1.045",
        "finalOG": "1.050",
        "initialFG": "1.010",
        "finalFG": "1.012",
        "initialBuGu": "0.50",
        "finalBuGu": "0.60"
    },
    {
        "name": "Brown Ale",
        "initialABV": "4.2",
        "finalABV": "6.2",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "18",
        "finalEBC": "35",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.25",
        "finalBuGu": "0.35"
    },
    {
        "name": "British Brown Ale",
        "initialABV": "4.2",
        "finalABV": "5.4",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "30",
        "finalEBC": "60",
        "initialOG": "1.040",
        "finalOG": "1.052",
        "initialFG": "1.008",
        "finalFG": "1.013",
        "initialBuGu": "0.50",
        "finalBuGu": "0.60"
    },
    {
        "name": "Brown Porter",
        "initialABV": "4.0",
        "finalABV": "5.4",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.040",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "California Common",
        "initialABV": "4.5",
        "finalABV": "5.5",
        "initialIBU": "30",
        "finalIBU": "45",
        "initialEBC": "10",
        "finalEBC": "20",
        "initialOG": "1.045",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Catarina Sour",
        "initialABV": "3.5",
        "finalABV": "5.5",
        "initialIBU": "10",
        "finalIBU": "20",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.040",
        "finalOG": "1.050",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "Classic American Pilsner",
        "initialABV": "4.5",
        "finalABV": "6.0",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "4",
        "finalEBC": "12",
        "initialOG": "1.044",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.42",
        "finalBuGu": "0.67"
    },
    {
        "name": "Cream Ale",
        "initialABV": "4.2",
        "finalABV": "5.6",
        "initialIBU": "8",
        "finalIBU": "20",
        "initialEBC": "4",
        "finalEBC": "12",
        "initialOG": "1.042",
        "finalOG": "1.055",
        "initialFG": "1.006",
        "finalFG": "1.012",
        "initialBuGu": "0.20",
        "finalBuGu": "0.35"
    },
    {
        "name": "Czech Dark Lager",
        "initialABV": "4.0",
        "finalABV": "5.8",
        "initialIBU": "18",
        "finalIBU": "30",
        "initialEBC": "30",
        "finalEBC": "70",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Czech Pale Lager",
        "initialABV": "4.0",
        "finalABV": "5.0",
        "initialIBU": "15",
        "finalIBU": "30",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.042",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.25",
        "finalBuGu": "0.45"
    },
    {
        "name": "Czech Pilsner",
        "initialABV": "4.2",
        "finalABV": "5.4",
        "initialIBU": "35",
        "finalIBU": "45",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.044",
        "finalOG": "1.056",
        "initialFG": "1.013",
        "finalFG": "1.017",
        "initialBuGu": "0.63",
        "finalBuGu": "0.80"
    },
    {
        "name": "Doppelbock",
        "initialABV": "7.0",
        "finalABV": "12.0",
        "initialIBU": "16",
        "finalIBU": "26",
        "initialEBC": "18",
        "finalEBC": "30",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Doppel IPA",
        "initialABV": "7.0",
        "finalABV": "9.0",
        "initialIBU": "60",
        "finalIBU": "100",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.80",
        "finalBuGu": "1.00"
    },
    {
        "name": "Dortmunder",
        "initialABV": "4.8",
        "finalABV": "6.0",
        "initialIBU": "23",
        "finalIBU": "30",
        "initialEBC": "12",
        "finalEBC": "20",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.35",
        "finalBuGu": "0.45"
    },
    {
        "name": "Dunkelweizen",
        "initialABV": "4.3",
        "finalABV": "5.6",
        "initialIBU": "10",
        "finalIBU": "20",
        "initialEBC": "14",
        "finalEBC": "23",
        "initialOG": "1.044",
        "finalOG": "1.056",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.25",
        "finalBuGu": "0.45"
    },
    {
        "name": "English Ale",
        "initialABV": "3.5",
        "finalABV": "6.0",
        "initialIBU": "15",
        "finalIBU": "40",
        "initialEBC": "10",
        "finalEBC": "22",
        "initialOG": "1.035",
        "finalOG": "1.060",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.60"
    },
    {
        "name": "English Barleywine",
        "initialABV": "8.0",
        "finalABV": "12.0",
        "initialIBU": "35",
        "finalIBU": "70",
        "initialEBC": "12",
        "finalEBC": "22",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.018",
        "finalFG": "1.030",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "English Bitter",
        "initialABV": "3.8",
        "finalABV": "5.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.035",
        "finalOG": "1.045",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.50",
        "finalBuGu": "0.60"
    },
    {
        "name": "English Brown Ale",
        "initialABV": "4.0",
        "finalABV": "5.6",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "30",
        "finalEBC": "60",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.40"
    },
    {
        "name": "English IPA",
        "initialABV": "5.0",
        "finalABV": "7.5",
        "initialIBU": "40",
        "finalIBU": "60",
        "initialEBC": "10",
        "finalEBC": "20",
        "initialOG": "1.050",
        "finalOG": "1.075",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.60",
        "finalBuGu": "1.00"
    },
    {
        "name": "English Pale Ale",
        "initialABV": "4.5",
        "finalABV": "6.0",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "10",
        "finalEBC": "20",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "English Porter",
        "initialABV": "4.0",
        "finalABV": "5.4",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "30",
        "finalEBC": "50",
        "initialOG": "1.040",
        "finalOG": "1.054",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "English Strong Ale",
        "initialABV": "5.5",
        "finalABV": "8.0",
        "initialIBU": "35",
        "finalIBU": "50",
        "initialEBC": "25",
        "finalEBC": "40",
        "initialOG": "1.060",
        "finalOG": "1.090",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "English Sweet Stout",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "30",
        "finalEBC": "40",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Euro Pale Lager",
        "initialABV": "4.2",
        "finalABV": "5.5",
        "initialIBU": "18",
        "finalIBU": "30",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Euro Strong Lager",
        "initialABV": "6.0",
        "finalABV": "9.0",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Foreign Extra Stout",
        "initialABV": "6.0",
        "finalABV": "8.0",
        "initialIBU": "35",
        "finalIBU": "60",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.060",
        "finalOG": "1.085",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "Flanders Red Ale",
        "initialABV": "5.5",
        "finalABV": "8.0",
        "initialIBU": "10",
        "finalIBU": "20",
        "initialEBC": "20",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Fruit Beer",
        "initialABV": "4.0",
        "finalABV": "8.0",
        "initialIBU": "8",
        "finalIBU": "40",
        "initialEBC": "10",
        "finalEBC": "50",
        "initialOG": "1.040",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.20",
        "finalBuGu": "0.50"
    },
    {
        "name": "German Bock",
        "initialABV": "6.3",
        "finalABV": "7.2",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "14",
        "finalEBC": "22",
        "initialOG": "1.060",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "German Helles",
        "initialABV": "4.7",
        "finalABV": "5.4",
        "initialIBU": "16",
        "finalIBU": "22",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.044",
        "finalOG": "1.050",
        "initialFG": "1.010",
        "finalFG": "1.012",
        "initialBuGu": "0.25",
        "finalBuGu": "0.40"
    },
    {
        "name": "German Märzen",
        "initialABV": "5.8",
        "finalABV": "6.3",
        "initialIBU": "18",
        "finalIBU": "24",
        "initialEBC": "10",
        "finalEBC": "25",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.40"
    },
    {
        "name": "German Pilsner (Pils)",
        "initialABV": "4.4",
        "finalABV": "5.2",
        "initialIBU": "22",
        "finalIBU": "40",
        "initialEBC": "6",
        "finalEBC": "12",
        "initialOG": "1.044",
        "finalOG": "1.050",
        "initialFG": "1.008",
        "finalFG": "1.013",
        "initialBuGu": "0.50",
        "finalBuGu": "0.80"
    },
    {
        "name": "German Schwarzbier",
        "initialABV": "4.4",
        "finalABV": "5.4",
        "initialIBU": "22",
        "finalIBU": "30",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.046",
        "finalOG": "1.056",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Gose",
        "initialABV": "4.0",
        "finalABV": "4.6",
        "initialIBU": "8",
        "finalIBU": "12",
        "initialEBC": "8",
        "finalEBC": "16",
        "initialOG": "1.030",
        "finalOG": "1.050",
        "initialFG": "1.004",
        "finalFG": "1.010",
        "initialBuGu": "0.10",
        "finalBuGu": "0.30"
    },
    {
        "name": "Grodziskie",
        "initialABV": "2.8",
        "finalABV": "4.2",
        "initialIBU": "8",
        "finalIBU": "18",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.040",
        "finalOG": "1.050",
        "initialFG": "1.004",
        "finalFG": "1.010",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Hazy IPA",
        "initialABV": "5.5",
        "finalABV": "8.0",
        "initialIBU": "40",
        "finalIBU": "60",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.060",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "Hefeweizen",
        "initialABV": "4.3",
        "finalABV": "5.6",
        "initialIBU": "8",
        "finalIBU": "15",
        "initialEBC": "8",
        "finalEBC": "16",
        "initialOG": "1.045",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.40"
    },
    {
        "name": "Herb and Spice Beer",
        "initialABV": "4.0",
        "finalABV": "7.0",
        "initialIBU": "8",
        "finalIBU": "25",
        "initialEBC": "8",
        "finalEBC": "40",
        "initialOG": "1.040",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.15",
        "finalBuGu": "0.40"
    },
    {
        "name": "Hefeweizen",
        "initialABV": "4.3",
        "finalABV": "5.6",
        "initialIBU": "10",
        "finalIBU": "18",
        "initialEBC": "6",
        "finalEBC": "15",
        "initialOG": "1.044",
        "finalOG": "1.052",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Imperial IPA",
        "initialABV": "7.5",
        "finalABV": "10.0",
        "initialIBU": "60",
        "finalIBU": "100",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.80",
        "finalBuGu": "1.00"
    },
    {
        "name": "Imperial Stout",
        "initialABV": "8.0",
        "finalABV": "12.0",
        "initialIBU": "35",
        "finalIBU": "80",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.080",
        "finalOG": "1.110",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "Irish Dry Stout",
        "initialABV": "3.8",
        "finalABV": "4.5",
        "initialIBU": "30",
        "finalIBU": "40",
        "initialEBC": "25",
        "finalEBC": "40",
        "initialOG": "1.040",
        "finalOG": "1.050",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.60",
        "finalBuGu": "0.80"
    },
    {
        "name": "Irish Red Ale",
        "initialABV": "4.2",
        "finalABV": "5.0",
        "initialIBU": "18",
        "finalIBU": "28",
        "initialEBC": "10",
        "finalEBC": "25",
        "initialOG": "1.040",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Irish Stout",
        "initialABV": "4.0",
        "finalABV": "4.5",
        "initialIBU": "25",
        "finalIBU": "45",
        "initialEBC": "60",
        "finalEBC": "100",
        "initialOG": "1.036",
        "finalOG": "1.044",
        "initialFG": "1.007",
        "finalFG": "1.011",
        "initialBuGu": "0.65",
        "finalBuGu": "1.00"
    },
    {
        "name": "Italian Grape Ale",
        "initialABV": "4.5",
        "finalABV": "7.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Japanese Rice Lager",
        "initialABV": "4.0",
        "finalABV": "5.5",
        "initialIBU": "15",
        "finalIBU": "30",
        "initialEBC": "4",
        "finalEBC": "8",
        "initialOG": "1.040",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Kentucky Common",
        "initialABV": "4.0",
        "finalABV": "5.5",
        "initialIBU": "15",
        "finalIBU": "25",
        "initialEBC": "12",
        "finalEBC": "25",
        "initialOG": "1.040",
        "finalOG": "1.050",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.25",
        "finalBuGu": "0.45"
    },
    {
        "name": "Kölsch",
        "initialABV": "4.4",
        "finalABV": "5.2",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "8",
        "finalEBC": "16",
        "initialOG": "1.044",
        "finalOG": "1.052",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.40",
        "finalBuGu": "0.50"
    },
    {
        "name": "Lambic",
        "initialABV": "5.0",
        "finalABV": "6.5",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "10",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.002",
        "finalFG": "1.012",
        "initialBuGu": "0.25",
        "finalBuGu": "0.45"
    },
    {
        "name": "Light Hybrid Beer",
        "initialABV": "3.0",
        "finalABV": "4.2",
        "initialIBU": "8",
        "finalIBU": "20",
        "initialEBC": "2",
        "finalEBC": "8",
        "initialOG": "1.030",
        "finalOG": "1.042",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.10",
        "finalBuGu": "0.30"
    },
    {
        "name": "Märzen",
        "initialABV": "5.8",
        "finalABV": "6.3",
        "initialIBU": "18",
        "finalIBU": "24",
        "initialEBC": "8",
        "finalEBC": "17",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Mild Ale",
        "initialABV": "3.0",
        "finalABV": "4.0",
        "initialIBU": "10",
        "finalIBU": "25",
        "initialEBC": "8",
        "finalEBC": "25",
        "initialOG": "1.030",
        "finalOG": "1.040",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Milk Stout",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "30",
        "finalEBC": "60",
        "initialOG": "1.040",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Munich Dunkel",
        "initialABV": "4.5",
        "finalABV": "5.6",
        "initialIBU": "18",
        "finalIBU": "28",
        "initialEBC": "14",
        "finalEBC": "28",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Munich Helles",
        "initialABV": "4.7",
        "finalABV": "5.4",
        "initialIBU": "16",
        "finalIBU": "22",
        "initialEBC": "6",
        "finalEBC": "12",
        "initialOG": "1.044",
        "finalOG": "1.050",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.40"
    },
    {
        "name": "New England IPA",
        "initialABV": "5.5",
        "finalABV": "8.0",
        "initialIBU": "40",
        "finalIBU": "60",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.060",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "New Zealand Pilsner",
        "initialABV": "4.2",
        "finalABV": "5.8",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "10",
        "finalEBC": "18",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Oud Bruin",
        "initialABV": "4.0",
        "finalABV": "8.0",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "20",
        "finalEBC": "50",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Oatmeal Stout",
        "initialABV": "4.2",
        "finalABV": "5.9",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "50",
        "finalEBC": "120",
        "initialOG": "1.048",
        "finalOG": "1.065",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.50",
        "finalBuGu": "0.65"
    },
    {
        "name": "Oberrhein Bier",
        "initialABV": "4.5",
        "finalABV": "5.5",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.046",
        "finalOG": "1.060",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Oktoberfest",
        "initialABV": "5.7",
        "finalABV": "6.3",
        "initialIBU": "18",
        "finalIBU": "24",
        "initialEBC": "8",
        "finalEBC": "17",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Old Ale",
        "initialABV": "5.8",
        "finalABV": "9.0",
        "initialIBU": "20",
        "finalIBU": "40",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Oyster Stout",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "30",
        "finalIBU": "40",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Pale Lager",
        "initialABV": "4.0",
        "finalABV": "5.0",
        "initialIBU": "10",
        "finalIBU": "18",
        "initialEBC": "4",
        "finalEBC": "8",
        "initialOG": "1.040",
        "finalOG": "1.050",
        "initialFG": "1.004",
        "finalFG": "1.010",
        "initialBuGu": "0.25",
        "finalBuGu": "0.40"
    },
    {
        "name": "Peated Smoked Porter",
        "initialABV": "4.5",
        "finalABV": "6.5",
        "initialIBU": "30",
        "finalIBU": "45",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.60",
        "finalBuGu": "0.70"
    },
    {
        "name": "Pilsner",
        "initialABV": "4.0",
        "finalABV": "5.5",
        "initialIBU": "25",
        "finalIBU": "45",
        "initialEBC": "8",
        "finalEBC": "16",
        "initialOG": "1.044",
        "finalOG": "1.050",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.50",
        "finalBuGu": "0.70"
    },
    {
        "name": "Porter",
        "initialABV": "4.0",
        "finalABV": "6.5",
        "initialIBU": "25",
        "finalIBU": "50",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Pumpkin Beer",
        "initialABV": "4.5",
        "finalABV": "7.0",
        "initialIBU": "10",
        "finalIBU": "20",
        "initialEBC": "15",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.20",
        "finalBuGu": "0.40"
    },
    {
        "name": "Rauchbier",
        "initialABV": "4.5",
        "finalABV": "6.0",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "20",
        "finalEBC": "40",
        "initialOG": "1.050",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.30",
        "finalBuGu": "0.40"
    },
    {
        "name": "Russian Imperial Stout",
        "initialABV": "8.0",
        "finalABV": "12.0",
        "initialIBU": "50",
        "finalIBU": "90",
        "initialEBC": "80",
        "finalEBC": "150",
        "initialOG": "1.075",
        "finalOG": "1.115",
        "initialFG": "1.018",
        "finalFG": "1.030",
        "initialBuGu": "0.65",
        "finalBuGu": "0.80"
    },
    {
        "name": "Red Ale",
        "initialABV": "4.5",
        "finalABV": "6.0",
        "initialIBU": "20",
        "finalIBU": "40",
        "initialEBC": "14",
        "finalEBC": "30",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Red IPA",
        "initialABV": "5.5",
        "finalABV": "7.5",
        "initialIBU": "40",
        "finalIBU": "70",
        "initialEBC": "14",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.60",
        "finalBuGu": "0.80"
    },
    {
        "name": "Rye Beer",
        "initialABV": "4.5",
        "finalABV": "7.0",
        "initialIBU": "30",
        "finalIBU": "60",
        "initialEBC": "10",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.40",
        "finalBuGu": "0.60"
    },
    {
        "name": "Saison",
        "initialABV": "5.0",
        "finalABV": "7.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.048",
        "finalOG": "1.065",
        "initialFG": "1.002",
        "finalFG": "1.012",
        "initialBuGu": "0.40",
        "finalBuGu": "0.70"
    },
    {
        "name": "Schwarzbier",
        "initialABV": "4.4",
        "finalABV": "5.4",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "35",
        "finalEBC": "50",
        "initialOG": "1.044",
        "finalOG": "1.056",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },    
    {
        "name": "Saison",
        "initialABV": "5.0",
        "finalABV": "7.0",
        "initialIBU": "20",
        "finalIBU": "35",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.048",
        "finalOG": "1.065",
        "initialFG": "1.002",
        "finalFG": "1.012",
        "initialBuGu": "0.40",
        "finalBuGu": "0.70"
    },
    {
        "name": "Scotch Ale",
        "initialABV": "6.0",
        "finalABV": "8.0",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "30",
        "finalEBC": "50",
        "initialOG": "1.060",
        "finalOG": "1.080",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.25",
        "finalBuGu": "0.40"
    },
    {
        "name": "Smoked Ale",
        "initialABV": "4.5",
        "finalABV": "7.5",
        "initialIBU": "20",
        "finalIBU": "40",
        "initialEBC": "15",
        "finalEBC": "30",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.018",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Sour Ale",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "5",
        "finalIBU": "20",
        "initialEBC": "8",
        "finalEBC": "18",
        "initialOG": "1.040",
        "finalOG": "1.060",
        "initialFG": "1.004",
        "finalFG": "1.010",
        "initialBuGu": "0.10",
        "finalBuGu": "0.30"
    },
    {
        "name": "Sparkling Ale",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "18",
        "finalIBU": "30",
        "initialEBC": "6",
        "finalEBC": "12",
        "initialOG": "1.040",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Specialty IPA",
        "initialABV": "6.0",
        "finalABV": "7.5",
        "initialIBU": "40",
        "finalIBU": "70",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.60",
        "finalBuGu": "0.80"
    },
    {
        "name": "Specialty Lager",
        "initialABV": "4.5",
        "finalABV": "6.5",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "8",
        "finalEBC": "20",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Starkbier",
        "initialABV": "6.5",
        "finalABV": "10.0",
        "initialIBU": "20",
        "finalIBU": "40",
        "initialEBC": "30",
        "finalEBC": "70",
        "initialOG": "1.070",
        "finalOG": "1.090",
        "initialFG": "1.014",
        "finalFG": "1.022",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Steam Beer",
        "initialABV": "4.5",
        "finalABV": "5.5",
        "initialIBU": "18",
        "finalIBU": "30",
        "initialEBC": "6",
        "finalEBC": "14",
        "initialOG": "1.045",
        "finalOG": "1.060",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.30",
        "finalBuGu": "0.50"
    },
    {
        "name": "Stout",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "35",
        "finalIBU": "50",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.020",
        "initialBuGu": "0.50",
        "finalBuGu": "0.75"
    },
    {
        "name": "Sweet Stout",
        "initialABV": "4.0",
        "finalABV": "6.0",
        "initialIBU": "25",
        "finalIBU": "40",
        "initialEBC": "40",
        "finalEBC": "80",
        "initialOG": "1.048",
        "finalOG": "1.065",
        "initialFG": "1.010",
        "finalFG": "1.015",
        "initialBuGu": "0.45",
        "finalBuGu": "0.65"
    },
    {
        "name": "Vienna Lager",
        "initialABV": "4.7",
        "finalABV": "5.5",
        "initialIBU": "18",
        "finalIBU": "30",
        "initialEBC": "10",
        "finalEBC": "16",
        "initialOG": "1.048",
        "finalOG": "1.055",
        "initialFG": "1.010",
        "finalFG": "1.014",
        "initialBuGu": "0.38",
        "finalBuGu": "0.60"
    },
    {
        "name": "West Coast IPA",
        "initialABV": "6.5",
        "finalABV": "7.5",
        "initialIBU": "50",
        "finalIBU": "70",
        "initialEBC": "8",
        "finalEBC": "14",
        "initialOG": "1.050",
        "finalOG": "1.070",
        "initialFG": "1.010",
        "finalFG": "1.016",
        "initialBuGu": "0.60",
        "finalBuGu": "0.80"
    },
    {
        "name": "Witbier",
        "initialABV": "4.5",
        "finalABV": "5.5",
        "initialIBU": "10",
        "finalIBU": "20",
        "initialEBC": "6",
        "finalEBC": "12",
        "initialOG": "1.044",
        "finalOG": "1.052",
        "initialFG": "1.008",
        "finalFG": "1.014",
        "initialBuGu": "0.20",
        "finalBuGu": "0.30"
    },
    {
        "name": "Zwickelbier",
        "initialABV": "4.5",
        "finalABV": "5.2",
        "initialIBU": "20",
        "finalIBU": "30",
        "initialEBC": "10",
        "finalEBC": "18",
        "initialOG": "1.044",
        "finalOG": "1.052",
        "initialFG": "1.008",
        "finalFG": "1.012",
        "initialBuGu": "0.30",
        "finalBuGu": "0.45"
    }
];