"""new hop field usage stage

Revision ID: 28163a2d30e7
Revises: 9839c2996807
Create Date: 2025-07-10 16:07:02.098036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28163a2d30e7'
down_revision = '9839c2996807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_fermentables', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)

    with op.batch_alter_table('recipe_hops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_stage', sa.String(length=15), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)

    with op.batch_alter_table('recipe_misc', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)

    with op.batch_alter_table('recipe_yeasts', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_yeasts', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)

    with op.batch_alter_table('recipe_misc', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)

    with op.batch_alter_table('recipe_hops', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.drop_column('usage_stage')

    with op.batch_alter_table('recipe_fermentables', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###
