"""Initial migration

Revision ID: 9839c2996807
Revises: 
Create Date: 2025-06-25 09:25:28.192471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9839c2996807'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('brewery', sa.String(length=60), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('batch_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_time', sa.Integer(), nullable=True),
    sa.Column('boil_time', sa.Integer(), nullable=True),
    sa.Column('boil_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('boil_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trub_loss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dead_space', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fermentables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ebc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('potential_extract', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('supplier', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('supplier', sa.String(length=40), nullable=True),
    sa.Column('alpha_acid_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('beta_acid_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_type', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('style', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yeasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('form', sa.String(length=15), nullable=True),
    sa.Column('attenuation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_range', sa.String(length=15), nullable=True),
    sa.Column('flavor_profile', sa.String(length=100), nullable=True),
    sa.Column('flocculation', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('batch_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('boil_time', sa.Integer(), nullable=False),
    sa.Column('boil_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('batch_time', sa.Integer(), nullable=True),
    sa.Column('boil_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dead_space', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trub_loss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_fermentables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ebc', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('potential_extract', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('supplier', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_hops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('alpha_acid_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('beta_acid_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('use_type', sa.String(length=15), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('boil_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_misc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('use', sa.String(length=15), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_yeasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.Column('form', sa.String(length=15), nullable=True),
    sa.Column('attenuation', sa.String(length=20), nullable=True),
    sa.Column('temperature_range', sa.String(length=15), nullable=True),
    sa.Column('flavor_profile', sa.Text(), nullable=True),
    sa.Column('flocculation', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_yeasts')
    op.drop_table('recipe_misc')
    op.drop_table('recipe_hops')
    op.drop_table('recipe_fermentables')
    op.drop_table('recipe_equipment')
    op.drop_table('yeasts')
    op.drop_table('recipes')
    op.drop_table('misc')
    op.drop_table('hops')
    op.drop_table('fermentables')
    op.drop_table('equipments')
    op.drop_table('users')
    # ### end Alembic commands ###
