"""add weight_unit to users

Revision ID: 371c818bf0e8
Revises: 28163a2d30e7
Create Date: 2025-08-08 23:16:57.026095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371c818bf0e8'
down_revision = '28163a2d30e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_unit', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weight_unit')

    # ### end Alembic commands ###
